---
# Configure codeready-containers

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ codeready-containers_services_enable }}"
  when: codeready-containers_enable_service
