---
# Template configuration files for codeready-containers

- name: Set SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    persistent: "{{ item.persistent | default('false') }}"
  loop: "{{ codeready-containers_selinux_booleans }}"
  when:
    - ansible_selinux.status == "enabled"
    - codeready-containers_enable_selinux
  become: true
